@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.Pdiddy973.AllTheCompressed.overlay;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
